/**
 * @import {Options} from 'micromark-extension-math'
 * @import {Construct, Previous, Resolver, State, Token, TokenizeContext, Tokenizer} from 'micromark-util-types'
 */

// To do: next major: clean spaces in HTML compiler.
// This has to be coordinated together with `mdast-util-math`.

import {ok as assert} from 'devlop'
import {asciiAlphanumeric, markdownLineEnding} from 'micromark-util-character'
import {codes, types} from 'micromark-util-symbol'

/**
 * @param {boolean} isLatexDelimiters
 *   When true, looks for modern LaTeX delimiters like \( ... \).
 *   When false, looks for legacy TeX delimiters like $...$
 * @param {Options | null | undefined} [options={}]
 *   Configuration (default: `{}`).
 * @returns {Construct}
 *   Construct.
 */
export function mathText(isLatexDelimiters, options) {
  const options_ = options || {}
  let single = options_.singleDollarTextMath

  if (single === null || single === undefined) {
    single = true
  }

  return {
    tokenize: tokenizeMathText,
    resolve: resolveMathText,
    previous,
    name: 'mathText'
  }

  /**
   * @this {TokenizeContext}
   * @type {Tokenizer}
   */
  function tokenizeMathText(effects, ok, nok) {
    const self = this
    let sizeOpen = 0
    /** @type {number} */
    let size
    /** @type {Token} */
    let token

    return start

    /**
     * Start of math (text).
     *
     * ```markdown
     * > | $a$
     *     ^
     * > | \$a$
     *      ^
     * ```
     *
     * @type {State}
     */
    function start(code) {
      if (isLatexDelimiters) {
        assert(code === codes.backslash, 'expected `\\`')
      }
      else {
        assert(code === codes.dollarSign, 'expected `$`')
        assert(previous.call(self, self.previous), 'expected correct previous')
      }

      effects.enter('mathText')
      effects.enter('mathTextSequence')
      return sequenceOpen(code)
    }

    /**
     * In opening sequence.
     *
     * ```markdown
     * > | $a$
     *     ^
     * ```
     *
     * @type {State}
     */

    function sequenceOpen(code) {
      if (isLatexDelimiters) {
        if (sizeOpen === 0) {
          assert(code === codes.backslash, 'expected `\\`')

          effects.consume(code)
          sizeOpen++
          return sequenceOpen
        }
        if (sizeOpen === 1) {
          if (code !== codes.leftParenthesis) {
            return nok(code)
          }

          effects.consume(code)
          sizeOpen++
          return sequenceOpen
        }
      }
      else {
        if (code === codes.dollarSign) {
          effects.consume(code)
          sizeOpen++
          return sequenceOpen
        }
      }

      // Not enough markers in the sequence.
      if (sizeOpen < 2) {
        // LaTeX requires exactly 2 characters: \(
        if (isLatexDelimiters) {
          return nok(code)
        }

        // Math allows $, but only when single is enabled.
        if (!single) {
          return nok(code)
        }
      }

      effects.exit('mathTextSequence')
      return between(code)
    }

    /**
     * Between something and something else.
     *
     * ```markdown
     * > | $a$
     *      ^^
     * ```
     *
     * @type {State}
     */
    function between(code) {
      if (code === codes.eof) {
        return nok(code)
      }

      // isLatexDelimiters  => allow \$, but detect \(
      // !isLatexDelimiters => allow \$, and detect $
      if (isLatexDelimiters) {
        if (code === codes.backslash) {
          token = effects.enter('mathTextSequence')
          size = 0
          return sequenceClose(code)
        }
      }
      else {
        if (code === codes.dollarSign) {
          // This check used to only look for code === codes.dollarSign to know if we might
          // be closing the sequence. However, we updated this check here to allow formulas
          // to use the \$ macro for representing dollar signs inside formulas.
          //
          // Example: $\$100$
          //
          // This is actually a fix we should try to upstream, but until then, we will
          // keep it in this patch.
          if (self.previous === codes.backslash) {
            // Manually consume the dollar sign as when we transition to data(...), if it
            // encounters a dollar sign it will bail out as it will think it is a token indicating
            // the completion of the inline-text closure.
            effects.enter('mathTextData')
            effects.consume(code)
            return data
          }

          // If a math text closure is about to be completed we want to make sure that
          // there isn't a leading space between the '$' as we are using this to help
          // distinguish between "real inline-math" and "dollar signs used in text".
          //
          // For example, with this check, we protect the following:
          //   A banana is $5 dollars and an apple is $2 dollars.
          //
          // For the most part, especially when generated by LLMs, inline text that uses
          // the legacy TeX approach of using $ as delimiters will never put spaces between
          // the delimiters and the formula starting.
          //
          // Always this: $x + y = z$
          // Never this:  $ x + y = z $
          //
          // So in this way, we can protect natural language usage of the dollar sign
          // while still allowing inline math formulas
          if (self.previous === codes.space) {
            return nok(code)
          }

          token = effects.enter('mathTextSequence')
          size = 0
          return sequenceClose(code)
        }
      }

      // Tabs don’t work, and virtual spaces don’t make sense.
      if (code === codes.space) {
        effects.enter('space')
        effects.consume(code)
        effects.exit('space')
        return between
      }

      if (markdownLineEnding(code)) {
        effects.enter(types.lineEnding)
        effects.consume(code)
        effects.exit(types.lineEnding)
        return between
      }

      // Data.
      effects.enter('mathTextData')
      return data(code)
    }

    /**
     * In data.
     *
     * ```markdown
     * > | $a$
     *      ^
     * ```
     *
     * @type {State}
     */
    function data(code) {
      if (
        code === codes.eof ||
        code === codes.space ||
        (isLatexDelimiters ? code === codes.backslash : code === codes.dollarSign) ||
        markdownLineEnding(code)
      ) {
        effects.exit('mathTextData')
        return between(code)
      }

      effects.consume(code)
      return data
    }

    /**
     * In closing sequence.
     *
     * ```markdown
     * > | `a`
     *       ^
     * ```
     *
     * @type {State}
     */
    function sequenceClose(code) {
      // More.
      if (isLatexDelimiters) {
        if (size === 0) {
          assert(code === codes.backslash, 'expected `\\`')

          effects.consume(code)
          size++
          return sequenceClose
        }
        if (size === 1) {
          if (code !== codes.rightParenthesis) {
            // Not a closing sequence. Treat the captured content as data and go back to data.
            token.type = 'mathTextData'
            return data(code)
          }

          effects.consume(code)
          size++
          return sequenceClose
        }
      }
      else {
        if (code === codes.dollarSign) {
          effects.consume(code)
          size++
          return sequenceClose
        }
      }

      // Done!
      if (size === sizeOpen) {
        // Check if the character immediately following the closing sequence is alphanumeric.
        // This helps distinguish between actual math like "$x$" and dollar amounts like "$1-$2" or "$USD".
        // If a closing $ is followed by an alphanumeric character, it's more likely to be
        // a dollar amount (e.g., "$10-$20", "$5USD") rather than math.
        if (!isLatexDelimiters && sizeOpen === 1 && asciiAlphanumeric(code)) {
          // This looks like a dollar amount, not math. Treat the sequence as data.
          token.type = 'mathTextData'
          return data(code)
        }

        effects.exit('mathTextSequence')
        effects.exit('mathText')
        return ok(code)
      }

      // More or less accents: mark as data.
      token.type = 'mathTextData'
      return data(code)
    }
  }
}

/** @type {Resolver} */
function resolveMathText(events) {
  let tailExitIndex = events.length - 4
  let headEnterIndex = 3
  /** @type {number} */
  let index
  /** @type {number | undefined} */
  let enter

  // If we start and end with an EOL or a space.
  if (
    (events[headEnterIndex][1].type === types.lineEnding ||
      events[headEnterIndex][1].type === 'space') &&
    (events[tailExitIndex][1].type === types.lineEnding ||
      events[tailExitIndex][1].type === 'space')
  ) {
    index = headEnterIndex

    // And we have data.
    while (++index < tailExitIndex) {
      if (events[index][1].type === 'mathTextData') {
        // Then we have padding.
        events[tailExitIndex][1].type = 'mathTextPadding'
        events[headEnterIndex][1].type = 'mathTextPadding'
        headEnterIndex += 2
        tailExitIndex -= 2
        break
      }
    }
  }

  // Merge adjacent spaces and data.
  index = headEnterIndex - 1
  tailExitIndex++

  while (++index <= tailExitIndex) {
    if (enter === undefined) {
      if (
        index !== tailExitIndex &&
        events[index][1].type !== types.lineEnding
      ) {
        enter = index
      }
    } else if (
      index === tailExitIndex ||
      events[index][1].type === types.lineEnding
    ) {
      events[enter][1].type = 'mathTextData'

      if (index !== enter + 2) {
        events[enter][1].end = events[index - 1][1].end
        events.splice(enter + 2, index - enter - 2)
        tailExitIndex -= index - enter - 2
        index = enter + 2
      }

      enter = undefined
    }
  }

  return events
}

/**
 * @this {TokenizeContext}
 * @type {Previous}
 */
function previous(code) {
  // If there is a previous code, there will always be a tail.
  return (
    code !== codes.dollarSign ||
    this.events[this.events.length - 1][1].type === types.characterEscape
  )
}
